version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
  web:
    build: .
    init: true
    entrypoint: /tmp/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:${PORT-3000}
    environment:
      - PORT
      - SENTRY_DSN
      - WAFP_RUN_ID
    volumes:
      - .:/tmp
    ports:
      - "${PORT-3000}:${PORT-3000}"
    depends_on:
      - db
