default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.*\.(md|rst)$
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.0.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
        additional_dependencies: ["isort[pyproject]"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        exclude: ^test/.*$
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
      - id: pylint
        additional_dependencies: ["isort[pyproject]"]
        exclude: ^test/.*$
        # disabled import-error as may be run out of environment with deps
        args: ["--disable=import-error"]
