version: '3'

services:
  mongo:
    image: mongo
  web:
    build: .
    init: true
    environment:
      - PORT
      - SENTRY_DSN
      - WAFP_RUN_ID
      - WAFP_FUZZER_ID
    ports:
      - "${PORT-3000}:5000"
    depends_on:
      - mongo
